# Используем базовый образ Ubuntu 22.04
FROM ubuntu:22.04

# Устанавливаем необходимые переменные среды
ENV DEBIAN_FRONTEND=noninteractive

# Установка необходимых пакетов для Ubuntu и Python
RUN apt update && apt install -y \
    python3 \
    python3-pip \
    postgresql-14 \ 
    libpq-dev \
    python3-dev

# Установка зависимостей Python
COPY requirements-postgres.txt /service/requirements-postgres.txt
COPY /DB_backup/work.backup /database/work.backup
RUN pip3 install --no-cache-dir -r /service/requirements-postgres.txt

# Обновляем значение listen_addresses в файле конфигурации
RUN sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/14/main/postgresql.conf
RUN echo "host    workforecastingservice     postgres     172.20.0.3/32    trust" >> /etc/postgresql/14/main/pg_hba.conf

#Настройка postgresql
RUN service postgresql start \
    && su - postgres -c "psql -c \"ALTER USER postgres WITH PASSWORD 'VzeVzeVze'\"" \
    && su - postgres -c "psql -c \"CREATE DATABASE workforecastingservice;\"" \
    && su - postgres -c "pg_restore -U postgres -d workforecastingservice /database/work.backup"

# Запуск БД
CMD service postgresql start && tail -f /dev/null